Addressed Greg's Additional Technical Comments
broadinstitute/profiling-resistance-mechanisms pull request #117
Opened 2021-09-15 20:18 UTC by yhan8

2021-09-21 14:06 UTC, gwaygenomics requested changes
Looks great @yhan8 - please clean up the required elements (delete new lines, that's all) in a couple scripts and lets your this contribution merged in!

2021-09-21 14:06 UTC, gwaygenomics commented on 3.resistance-signature/scripts/nbconverted/8.1.last-batch-compile-otherclone-datase.py
> +full_df_val = full_df_val.query("Metadata_clone_number not in @tx_clones")
woo!

2021-09-21 14:06 UTC, gwaygenomics commented on 3.resistance-signature/scripts/nbconverted/8.1.last-batch-compile-otherclone-datase.py
> +full_df_val = full_df_val.query("Metadata_clone_number not in @tx_clones")
more pythonic for sure!

2021-09-21 14:06 UTC, gwaygenomics commented on 3.resistance-signature/scripts/nbconverted/8.compile-otherclone-dataset.py
> +
This is what happens with extra new lines :)

2021-09-22 17:37 UTC, yhan8 commented on 2.describe-data/1.merge-datasets-gct.ipynb
> +   "source": []
Thanks Greg, all set :)

2021-09-22 17:42 UTC, merged